### ISSUE TITLE
Python 3.11 install failure due to lack of support by used dependency version: MDAnalysis~=2.3.0

### ISSUE THREAD

**Issue by Al-per** [bkellerlab/molecularRotationalGrids#44]
### What happened?
Installing molgri on a system running Python 3.11 causes pip to throw the error:

```
Collecting MDAnalysis~=2.3.0
...
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 255
  ╰─> [5 lines of output]
      Attempting to autodetect OpenMP support... Compiler supports OpenMP
      Will attempt to use Cython.
      *** package "numpy" not found ***
      MDAnalysis requires a version of NumPy (>=1.20.0), even for setup.
      Please get it from http://numpy.scipy.org/ or install it through your package manager.
...
```
Checking the MDAnalysis [releases](https://github.com/MDAnalysis/mdanalysis/releases/tag/package-2.4.0) shows that MDAnalysis==2.4.0 is the first version with official Python 3.11 support.

### Any Solutions?
Editing the molgri requirements file and updating the dependency to `MDAnalysis ~=2.4.0` fixes the install error and allows for normal installation. 

Finding the root cause did not yield fruitful results.

Using version 2.4.0 of MDAnalysis and running the tests did not yield different results to tests run on version 2.3.0. 

Results:

```
...
tests/test_polytopes.py:252: AssertionError
...
FAILED tests/test_polytopes.py::test_sorting - AssertionError: assert False
===...===1 failed, 64 passed, 67 warnings in 622.71s (0:10:22)===...===
```
No attempts of trying a newer version of MDAnalysis were made.

### Environment
- Fedora 37 running molgri 1.3.5/1.3.6 using Python 3.11.3
- Debian 11 running molgri 1.3.5 using Python 3.10 .11/ 3.11.3

Tests and installation attempts on both systems.
Solution attempts on both systems but only with molgri version 1.3.5.

**Comment by hanazupan** [comment]
Fixed in v1.3.8
